spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

server:
  email: bluedskim@gmail.com
  servlet:
    context-path: /ee
  port: 8080

# https://springframework.guru/using-yaml-in-spring-boot-to-configure-logback/
logging:
  level:
    org.dskim: DEBUG
  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5p) %green(%c{1}):%L - %m%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5p) %green(%M):%L - %m%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5p) %green(%c{1}.%M):%L - %m%n"

blog:
  rootDir: /home/bluedskim/IdeaProjects/egloosexodus/blogRootDir
  # 잘못하면 DDOS공격으로 오인 받을 수 있으므로 적당히 쉰다. (초)
  minSleepTime: 1
  # 다운로드 받은 불로그 보유기간. 1440 : 하루 / 1440000 : 1000일
  durationMin: 1440000

senderMailId: egloos.exodus
senderMailpw: ?#H1xkUc6V

---

spring:
  profiles: dev

hugo:
  resourcesDir: /home/bluedskim/IdeaProjects/egloosexodus/hugoResources

---

spring:
  profiles: prod

hugo:
  resourcesDir:

blog:
  # 다운로드 받은 불로그 보유기간. 1440 : 하루 / 1440000 : 1000일
  durationMin: 1440000