spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://samba.iptime.org:9096/ee_dev
    username: ee
    password: DcvqyQDtuFt3C73m

server:
  email: bluedskim@gmail.com
  servlet:
    context-path: /ee
  port: 8080

# https://springframework.guru/using-yaml-in-spring-boot-to-configure-logback/
logging:
  level:
    org.dskim: DEBUG
  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5p) %green(%c{1}):%L - %m%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5p) %green(%M):%L - %m%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5p) %green(%c{1}.%M):%L - %m%n"

blog:
  rootDir: /home/bluedskim/Documents/dev/egloosexodus/blogRootDir
  # 잘못하면 DDOS공격으로 오인 받을 수 있으므로 적당히 쉰다. (초)
  minSleepTime: 1
  # 다운로드 받은 불로그 보유기간. 1440 : 하루 / 1440000 : 1000일
  durationMin: 1440000
  checkOwner: true
  checkOwnerString: exodus

senderMailId: egloos.exodus
senderMailpw: ?#H1xkUc6V

nitrite:
#  path: /tmp/egloosExodus.nitrite
  path: /home/bluedskim/IdeaProjects/egloosexodus/egloosExodus.nitrite

version: beta
#maxPostCount: 2147483647
maxPostCount: 10

---

spring:
  profiles: dev

hugo:
  resourcesDir: /home/bluedskim/IdeaProjects/egloosexodus/hugoResources

---

spring:
  profiles: prod
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://samba.iptime.org:9096/ee_prod
    username: ee
    password: DcvqyQDtuFt3C73m

logging:
  file: logs/ee.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5p) %green(%c{1}.%M):%L - %m%n"

hugo:
  resourcesDir:

blog:
  # 다운로드 받은 불로그 보유기간. 1440 : 하루 / 1440000 : 1000일
  durationMin: 1440





